version: "3"
services:
  grpc-server:
    build:
      context: ./grpc-server
      dockerfile: Dockerfile
    volumes:
      - /app/grpc-server/node_modules
      - ./grpc-server/:/app/grpc-server
    expose:
      - "5000"
    ports:
      - "5000:5000"
  grpc-client:
    build:
      context: ./grpc-client
      dockerfile: Dockerfile
    volumes:
      - /app/grpc-client/node_modules
      - ./grpc-client/:/app/grpc-client
    ports:
      - "3000:3000"
    depends_on:
      - grpc-server
